name: rjd-sra-tools
title: rjd-sra-tools
version: '3.0.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: Toolkit from NCBI for using Sequence Read Archives data.
description: |
          " The SRA Toolkit and SDK from NCBI is a collection of tools and libraries for using data in the INSDC Sequence Read Archives.."
          *  The description above refers to the software:
          * I have packaged the software as a snap for **personal use** but I have made the snap available for free.
          * I do not maintain the software itself. I only maintain the snap packaging. Please report software bugs to the maintainers.
          * Report snap-specific bugs to me.
            * I _DO_ use this snap. It _has been superficially tested_ on my system. I __do not__ track the latest version.
            * __The snap has not been fully tested__
            * Packaging 'style' : tarball build for linux machines.
            * License refers to the original software, not the snapcraft 'code'.
            * More info:
            * Run the following to rename the snap
            ```sudo snap alias rjd-sra-tools.<function> <function>```
            At the moment only a few commands are exposed.

website: https://github.com/RJDan/rjd-sra-tools_snap
source-code : https://github.com/RJDan/rjd-sra-tools_snap
icon: Icon_230417.svg

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
#license: GPL-3.0-only
base: core22 # the base snap is the execution environment for this snap
architectures:
    - amd64

apps:
# list of functions that come with the toolkit
 abi-dump:
        command: abi-dump
        plugs:
          - home
          - network
          - removable-media
# abi-dump.3
# abi-dump.3.0.5
 abi-load:
        command: abi-load
        plugs:
          - home
          - network
          - removable-media
# abi-load.3
# abi-load.3.0.5
 align-info:
        command: align-info
        plugs:
          - home
          - network
          - removable-media
# align-info.3
# align-info.3.0.5
 # ar.3:
 #        command: ar.3
 #        plugs:
 #          - home
 #          - network
 #          - removable-media
# ar.3.0.5
 bam-load:
        command: bam-load
        plugs:
          - home
          - network
          - removable-media
# bam-load.3
# bam-load.3.0.5
# bison.yacc
 cache-mgr:
        command: cache-mgr
        plugs:
          - home
          - network
          - removable-media
# cache-mgr.3
# cache-mgr.3.0.5
#  cg-load:
#         command: cg-load
#         plugs:
#           - home
#           - network
#           - removable-media
# # cg-load.3
# # cg-load.3.0.5
#  dbmeta:
#         command: dbmeta
#           - home
#           - network
#           - removable-media
 dump-ref-fasta:
        command: dump-ref-fasta
        plugs:
          - home
          - network
          - removable-media
# dump-ref-fasta.3
# dump-ref-fasta.3.0.5
 fasterq-dump:
        command: fasterq-dump
        plugs:
          - home
          - network
          - removable-media
# fasterq-dump-orig.3.0.5
# fasterq-dump.3
# fasterq-dump.3.0.5
 fastq-dump:
        command: fastq-dump
        plugs:
          - home
          - network
          - removable-media
# fastq-dump-orig.3.0.5
# fastq-dump.3
# fastq-dump.3.0.5
 fastq-load:
        command: fastq-load
        plugs:
          - home
          - network
          - removable-media
# fastq-load.3
# fastq-load.3.0.5
 # flex:
 #        command: flex
 #          - home
 #          - network
 #          - removable-media
# flex++
 helicos-load:
        command: helicos-load
        plugs:
          - home
          - network
          - removable-media
# helicos-load.3
# helicos-load.3.0.5
 illumina-dump:
        command: illumina-dump
        plugs:
          - home
          - network
          - removable-media
# illumina-dump.3
# illumina-dump.3.0.5
 illumina-load:
        command: illumina-load
        plugs:
          - home
          - network
          - removable-media
# illumina-load.3
# illumina-load.3.0.5
 # kar:
 #        command: kar
 #          - home
 #          - network
 #          - removable-media
 # kdbmeta.3:
 #        command: kdbmeta.3
 #        plugs:
 #          - home
 #          - network
 #          - removable-media
# kdbmeta.3.0.5
 latf-load:
        command: latf-load
        plugs:
          - home
          - network
          - removable-media
# latf-load.3
# latf-load.3.0.5
 # lex:
 #        command: lex
 #          - home
 #          - network
 #          - removable-media
 # m4:
 #        command: m4
 #          - home
 #          - network
 #          - removable-media
 # ncbi:
 #        command: ncbi
 #          - home
 #          - network
 #          - removable-media
 pacbio-load:
        command: pacbio-load
        plugs:
          - home
          - network
          - removable-media
# pacbio-load.3
# pacbio-load.3.0.5
 prefetch:
        command: prefetch
          - home
          - network
          - removable-media
# prefetch-orig.3.0.5
# prefetch.3
# prefetch.3.0.5
 rcexplain:
        command: rcexplain
          - home
          - network
          - removable-media
# rcexplain.3
# rcexplain.3.0.5
 sam-dump:
        command: sam-dump
        plugs:
          - home
          - network
          - removable-media
# sam-dump-orig.3.0.5
# sam-dump.3
# sam-dump.3.0.5
 sff-dump:
        command: sff-dump
        plugs:
          - home
          - network
          - removable-media
# sff-dump.3
# sff-dump.3.0.5
 sff-load:
        command: sff-load
        plugs:
          - home
          - network
          - removable-media
# sff-load.3
# sff-load.3.0.5
 sra-pileup:
        command: sra-pileup
        plugs:
          - home
          - network
          - removable-media
# sra-pileup-orig.3.0.5
# sra-pileup.3
# sra-pileup.3.0.5
 sra-search:
        command: sra-search
        plugs:
          - home
          - network
          - removable-media
# sra-search.3
# sra-search.3.0.5
 sra-sort:
        command: sra-sort
        plugs:
          - home
          - network
          - removable-media
 # sra-sort-cg:
 #        command: sra-sort-cg
 #        plugs:
 #          - home
 #          - network
 #          - removable-media
# sra-sort-cg.3
# sra-sort-cg.3.0.5
# sra-sort.3
# sra-sort.3.0.5
 sra-stat:
        command: sra-stat
        plugs:
          - home
          - network
          - removable-media
# sra-stat.3
# sra-stat.3.0.5
 srapath:
        command: srapath
          - home
          - network
          - removable-media
# srapath-orig.3.0.5
# srapath.3
# srapath.3.0.5
# sratools.3.0.5
 srf-load:
        command: srf-load
        plugs:
          - home
          - network
          - removable-media
# srf-load.3
# srf-load.3.0.5
 test-sra:
        command: test-sra
        plugs:
          - home
          - network
          - removable-media
# test-sra.3
# test-sra.3.0.5
# vdb-config
# vdb-config.3
# vdb-config.3.0.5
 vdb-copy:
        command: vdb-copy
        plugs:
          - home
          - network
          - removable-media
# vdb-copy.3
# vdb-copy.3.0.5
 vdb-decrypt:
        command: vdb-decrypt
        plugs:
          - home
          - network
          - removable-media
# vdb-decrypt.3
# vdb-decrypt.3.0.5
 vdb-dump:
        command: vdb-dump
        plugs:
          - home
          - network
          - removable-media
# vdb-dump-orig.3.0.5
# vdb-dump.3
# vdb-dump.3.0.5
 vdb-encrypt:
        command: vdb-encrypt
        plugs:
          - home
          - network
          - removable-media
# vdb-encrypt.3
# vdb-encrypt.3.0.5
 vdb-lock:
        command: vdb-lock
        plugs:
          - home
          - network
          - removable-media
# vdb-lock.3
# vdb-lock.3.0.5
 vdb-unlock:
        command: vdb-unlock
        plugs:
          - home
          - network
          - removable-media
# vdb-unlock.3
# vdb-unlock.3.0.5
 vdb-validate:
        command: vdb-validate
        plugs:
          - home
          - network
          - removable-media
# vdb-validate.3
# vdb-validate.3.0.5
        environment:
            JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-${SNAPCRAFT_TARGET_ARCH}
            JAVA_TOOL_OPTIONS: "-Duser.home=$SNAP_USER_COMMON"
#            PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH

# The `layout` ensures that files can be found by applications where they are expected by the toolkit or application.
#    layout:
    #     # # Other, generally useful paths
    #     # /etc/fonts:
    #     #   bind: $SNAP/etc/fonts
    #     # /usr/share/fonts:
    #     #   bind: $SNAP/usr/share/fonts
    #     # /usr/share/icons:
    #     #   bind: $SNAP/usr/share/icons
    #     # /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/lapack:
    #     #   bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/lapack
    #     # /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/blas:
    #     #   bind: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/blas
    #     /usr/bin/python:
    #       bind: $SNAP/usr/bin/python


parts:
    sra-tools:
      source:  https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.0.5/sratoolkit.3.0.5-ubuntu64.tar.gz
      plugin: dump
      build-packages:
       - less
       - tree
       - libc6-dev
       - zlib1g-dev
       - libxml2-dev
       - libbison-dev
       - libfl-dev
       - libssl-dev
       - python3 # needed for checking the install and nothing else
       - python3-dev # needed for checking the install and nothing else
      stage-packages:
       - flex
       - openssl
       - libcrypt1
       - bison
       - libxml2
       - libc6 #Automatically Tuned Linear Algebra Software, documentation
      # filesets:
      #      binary:
      #      - sra-tools
      organize:
            "Icon_230417.svg" : snap/Icon_230417.svg
            "bin" : usr/local/bin
      override-build: |
                # moving binaries from build to install
                cp -r ${SNAPCRAFT_PART_BUILD}/bin ${SNAPCRAFT_PART_INSTALL}/bin
      # override-stage: |
      #           cp -r ${SNAPCRAFT_PART_INSTALL}/usr ${STAGE}/
      stage: # stage runs after organise
      - usr/local/bin
#            - $binary
      prime:
      - usr/local/bin
#         - $binary

