name: rjd-sra-tools
title: SRA Tools
version: '3.0.5' # just for humans, typically '1.2+git' or '1.3.2'
summary: Toolkit from NCBI for using Sequence Read Archives data.
description: |
          " The SRA Toolkit and SDK from NCBI is a collection of tools and libraries for using data in the INSDC Sequence Read Archives.."
          *  The description above refers to the software: https://github.com/ncbi/sra-tools
          * I have packaged the software as a snap for **personal use** but I have made the snap available for free.
          * I do not maintain the software itself. I only maintain the snap packaging. Please report software bugs to the maintainers.
          * Report snap-specific bugs to me.
            * I _DO_ use this snap. It _HAS BEEN SUPERFICIALLY_ tested on my system. I __do not__ track the latest version.
            * __The snap has not been fully tested__
            * Packaging 'style' : tarball build for linux machines.
            * License refers to the original software, not the snapcraft 'code'.
            * More info:
            * Run the following to rename the snap commands to whatever you want.
                ```sudo snap alias rjd-sra-tools.<function> <function>```
#            * Install the snap with the flag '--prefer' to use the default aliases.
#            ```sudo snap install rjd-sra-tools --prefer```

website: https://github.com/RJDan/rjd-sra-tools_snap
source-code : https://github.com/RJDan/rjd-sra-tools_snap
contact : https://github.com/RJDan/rjd-sra-tools_snap
icon: Icon.svg

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
#license: GPL-3.0-only
base: core22 # the base snap is the execution environment for this snap
architectures:
    - amd64

apps:
# list of functions that come with the toolkit
 abi-dump:
        command: usr/local/bin/abi-dump
        aliases: [ abi-dump ]
        plugs:
          - home
          - network
          - removable-media
# abi-dump.3
# abi-dump.3.0.5
 abi-load:
        command: usr/local/bin/abi-load
        aliases: [ abi-load ]
        plugs:
          - home
          - network
          - removable-media
# abi-load.3
# abi-load.3.0.5
 align-info:
        command: usr/local/bin/align-info
        aliases: [ align-info ]
        plugs:
          - home
          - network
          - removable-media
# align-info.3
# align-info.3.0.5
 # ar.3:
 #        command: usr/local/bin/ar.3
#  aliases: [ ar.3 ]
 #        plugs:
 #          - home
 #          - network
 #          - removable-media
# ar.3.0.5
 bam-load:
        command: usr/local/bin/bam-load
        aliases: [ bam-load ]
        plugs:
          - home
          - network
          - removable-media
# bam-load.3
# bam-load.3.0.5
# bison.yacc
 cache-mgr:
        command: usr/local/bin/cache-mgr
        aliases: [ cache-mgr ]
        plugs:
          - home
          - network
          - removable-media
# cache-mgr.3
# cache-mgr.3.0.5
 cg-load:
        command: usr/local/bin/cg-load
        aliases: [ cg-load ]
        plugs:
          - home
          - network
          - removable-media
# # cg-load.3
# # cg-load.3.0.5
 # dbmeta: # error, does not exist
 #        command: usr/local/bin/dbmeta
#  aliases: [  dbmeta ] # error, does not exis ]
 #          - home
 #          - network
 #          - removable-media
 dump-ref-fasta:
        command: usr/local/bin/dump-ref-fasta
        aliases: [ dump-ref-fasta ]
        plugs:
          - home
          - network
          - removable-media
# dump-ref-fasta.3
# dump-ref-fasta.3.0.5
 fasterq-dump:
        command: usr/local/bin/fasterq-dump
        aliases: [ fasterq-dump ]
        plugs:
          - home
          - network
          - removable-media
# fasterq-dump-orig.3.0.5
# fasterq-dump.3
# fasterq-dump.3.0.5
 fastq-dump:
        command: usr/local/bin/fastq-dump
        aliases: [ fastq-dump ]
        plugs:
          - home
          - network
          - removable-media
# fastq-dump-orig.3.0.5
# fastq-dump.3
# fastq-dump.3.0.5
 fastq-load:
        command: usr/local/bin/fastq-load
        aliases: [ fastq-load ]
        plugs:
          - home
          - network
          - removable-media
# fastq-load.3
# fastq-load.3.0.5
 # flex: # error, does not exist
 #        command: usr/local/bin/flex
#  aliases: [ flex] # error, does not exis ]
 #          - home
 #          - network
 #          - removable-media
# flex++
 helicos-load:
        command: usr/local/bin/helicos-load
        aliases: [ helicos-load ]
        plugs:
          - home
          - network
          - removable-media
# helicos-load.3
# helicos-load.3.0.5
 illumina-dump:
        command: usr/local/bin/illumina-dump
        aliases: [ illumina-dump ]
        plugs:
          - home
          - network
          - removable-media
# illumina-dump.3
# illumina-dump.3.0.5
 illumina-load:
        command: usr/local/bin/illumina-load
        aliases: [ illumina-load ]
        plugs:
          - home
          - network
          - removable-media
# illumina-load.3
# illumina-load.3.0.5
 kar:
        command: usr/local/bin/kar
        aliases: [ kar ]
          - home
          - network
          - removable-media
 # kdbmeta.3: # error with app name, can't have '.'
 #        command: usr/local/bin/kdbmeta.3
#  aliases: [  kdbmeta.3 ]: # error with app name, can't have '. ]
 #        plugs:
 #          - home
 #          - network
 #          - removable-media
# kdbmeta.3.0.5
 latf-load:
        command: usr/local/bin/latf-load
        aliases: [ latf-load ]
        plugs:
          - home
          - network
          - removable-media
# latf-load.3
# latf-load.3.0.5
 # lex: # error, does not exist
 #        command: usr/local/bin/lex
#  aliases: [  lex ] # error, does not exis ]
 #          - home
 #          - network
 #          - removable-media
 # m4: # error, does not exist
 #        command: usr/local/bin/m4
  #aliases: [  m4 ] # error, does not exis ]
 #          - home
 #          - network
 #          - removable-media
 ncbi:
        command: usr/local/bin/ncbi
        aliases: [ ncbi ]
          - home
          - network
          - removable-media
 pacbio-load:
        command: usr/local/bin/pacbio-load
        aliases: [ pacbio-load ]
        plugs:
          - home
          - network
          - removable-media
# pacbio-load.3
# pacbio-load.3.0.5
 prefetch:
        command: usr/local/bin/prefetch
        aliases: [ prefetch ]
          - home
          - network
          - removable-media
# prefetch-orig.3.0.5
# prefetch.3
# prefetch.3.0.5
 rcexplain:
        command: usr/local/bin/rcexplain
        aliases: [ rcexplain ]
          - home
          - network
          - removable-media
# rcexplain.3
# rcexplain.3.0.5
 sam-dump:
        command: usr/local/bin/sam-dump
        aliases: [ sam-dump ]
        plugs:
          - home
          - network
          - removable-media
# sam-dump-orig.3.0.5
# sam-dump.3
# sam-dump.3.0.5
 sff-dump:
        command: usr/local/bin/sff-dump
        aliases: [ sff-dump ]
        plugs:
          - home
          - network
          - removable-media
# sff-dump.3
# sff-dump.3.0.5
 sff-load:
        command: usr/local/bin/sff-load
        aliases: [ sff-load ]
        plugs:
          - home
          - network
          - removable-media
# sff-load.3
# sff-load.3.0.5
 sra-pileup:
        command: usr/local/bin/sra-pileup
        aliases: [ sra-pileup ]
        plugs:
          - home
          - network
          - removable-media
# sra-pileup-orig.3.0.5
# sra-pileup.3
# sra-pileup.3.0.5
 sra-search:
        command: usr/local/bin/sra-search
        aliases: [ sra-search ]
        plugs:
          - home
          - network
          - removable-media
# sra-search.3
# sra-search.3.0.5
 sra-sort:
        command: usr/local/bin/sra-sort
        aliases: [ sra-sort ]
        plugs:
          - home
          - network
          - removable-media
 sra-sort-cg:
        command: usr/local/bin/sra-sort-cg
        aliases: [ sra-sort-cg ]
        plugs:
          - home
          - network
          - removable-media
# sra-sort-cg.3
# sra-sort-cg.3.0.5
# sra-sort.3
# sra-sort.3.0.5
 sra-stat:
        command: usr/local/bin/sra-stat
        aliases: [ sra-stat ]
        plugs:
          - home
          - network
          - removable-media
# sra-stat.3
# sra-stat.3.0.5
 srapath:
        command: usr/local/bin/srapath
        aliases: [ srapath ]
          - home
          - network
          - removable-media
# srapath-orig.3.0.5
# srapath.3
# srapath.3.0.5
# sratools.3.0.5
 srf-load:
        command: usr/local/bin/srf-load
        aliases: [ srf-load ]
        plugs:
          - home
          - network
          - removable-media
# srf-load.3
# srf-load.3.0.5
 test-sra:
        command: usr/local/bin/test-sra
        aliases: [ test-sra ]
        plugs:
          - home
          - network
          - removable-media
# test-sra.3
# test-sra.3.0.5
 vdb-config:
        command: usr/local/bin/vdb-config
        aliases: [ vdb-config ]
        plugs:
          - home
          - network
          - removable-media
# vdb-config.3
# vdb-config.3.0.5
 vdb-copy:
        command: usr/local/bin/vdb-copy
        aliases: [ vdb-copy ]
        plugs:
          - home
          - network
          - removable-media
# vdb-copy.3
# vdb-copy.3.0.5
 vdb-decrypt:
        command: usr/local/bin/vdb-decrypt
        aliases: [ vdb-decrypt ]
        plugs:
          - home
          - network
          - removable-media
# vdb-decrypt.3
# vdb-decrypt.3.0.5
 vdb-dump:
        command: usr/local/bin/vdb-dump
        aliases: [ vdb-dump ]
        plugs:
          - home
          - network
          - removable-media
# vdb-dump-orig.3.0.5
# vdb-dump.3
# vdb-dump.3.0.5
 vdb-encrypt:
        command: usr/local/bin/vdb-encrypt
        aliases: [ vdb-encrypt ]
        plugs:
          - home
          - network
          - removable-media
# vdb-encrypt.3
# vdb-encrypt.3.0.5
 vdb-lock:
        command: usr/local/bin/vdb-lock
        aliases: [ vdb-lock ]
        plugs:
          - home
          - network
          - removable-media
# vdb-lock.3
# vdb-lock.3.0.5
 vdb-unlock:
        command: usr/local/bin/vdb-unlock
        aliases: [ vdb-unlock ]
        plugs:
          - home
          - network
          - removable-media
# vdb-unlock.3
# vdb-unlock.3.0.5
 vdb-validate:
        command: usr/local/bin/vdb-validate
        aliases: [ vdb-validate ]
        plugs:
          - home
          - network
          - removable-media
# vdb-validate.3
# vdb-validate.3.0.5
        environment:
            HOME: ${SNAP_USER_COMMON}
            LD_LIBRARY_PATH:    $SNAP/rjd-analysis-depend-libs:$SNAP/graphics/lib:${LD_LIBRARY_PATH}
            NCBI_HOME: ${SNAP_USER_COMMON}/.ncbi
#                <NCBI_SETTINGS>"/home/rjd/snap/rjd-sra-tools/x1/.ncbi/user-settings.mkfg"</NCBI_SETTINGS>
            JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-${SNAPCRAFT_TARGET_ARCH}
            JAVA_TOOL_OPTIONS: "-Duser.home=$SNAP_USER_COMMON"

plugs:
  rjd-analysis-depend:
    interface: content
    content: rjd-analysis-depend-0-0-1-2204 # need to check where the libs actually are
    target: $SNAP/rjd-analysis-depend-libs
    default-provider: rjd-analysis-depend

parts:
    sra-tools:
      source:  https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.0.5/sratoolkit.3.0.5-ubuntu64.tar.gz
      plugin: dump
      stage-snaps:
        - rjd-analysis-depend
      # filesets:
      #      binary:
      #      - sra-tools
      organize:
            "Icon_230417.svg" : snap/Icon_230417.svg
            "bin" : usr/local/bin
      override-build: |
                # moving binaries from build to install
                cp -r ${SNAPCRAFT_PART_BUILD}/bin ${SNAPCRAFT_PART_INSTALL}/bin
      # override-stage: |
      #           cp -r ${SNAPCRAFT_PART_INSTALL}/usr ${STAGE}/
      stage: # stage runs after organise
      - usr/local/bin
#            - $binary
      prime:
      - usr/local/bin
#         - $binary

